### ISSUE TITLE
Return or not returning array of vectors?

### ISSUE THREAD

**Issue by brmarkus** [cadin/line-wobbler#1]
What's the idea of only some of the `drawXYZ()` methods to return an array of vectors?

`PVector[] drawLine(...)` versus `void drawRect(...)`?

Thought about using the `line-wobbler` in a bigger context, where the subpoints of each line, poly-lines, i.e. each shape would be of interest.

**Comment by cadin** [comment]
Hmm, mostly just that I only needed them in that context I guess.
I'll accept a pull request if you want to add them elsewhere.

**Comment by brmarkus** [comment]
Got you. Thanks.
No worries.
